# fly.toml app configuration file generated for apply-here on 2025-04-22T21:49:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'apply-here'
primary_region = 'ord'

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="apply_here_data"
  destination="/data"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
